// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noqoxwgryffazbmeucah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcW94d2dyeWZmYXpibWV1Y2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTI4MTQsImV4cCI6MjA3MDA2ODgxNH0.FUMA6wKsTMAA3_9U3sv4KlDHZwwIzC-VWXU2eqfVIUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});